{
 "title": "historical dashboard",
 "time": { "from": "2024-12-27T08:00:00.000Z", "to": "2024-12-29T18:45:00.000Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "USER1_db",
     "rawSql": "SELECT diseases_detected, timestamp, plant_id, plate_id FROM USER1_db.Historical_Data LIMIT 50 "
    }
   ]
  },
  {
   "title": "history of sensors readings ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "USER1_db",
     "rawSql": "SELECT temperature, humidity, timestamp, ec, ph FROM USER1_db.Historical_Data ORDER BY timestamp LIMIT 100 "
    }
   ]
  },
  {
   "title": "history of plants and plates",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "USER1_db",
     "rawSql": "SELECT plant_id, plate_id, timestamp FROM USER1_db.Historical_Data LIMIT 50 "
    }
   ]
  },
  {
   "title": "plants yield",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "USER1_db",
     "rawSql": "SELECT weight, plant_id, active_ingredient_level FROM USER1_db.Plant_Quality LIMIT 50 "
    }
   ]
  }
 ]
}